### ISSUE TITLE
May I ask for the runtime environment config

### ISSUE THREAD

**Issue by lzxzy** [ruiguo-bio/midi-miner#2]
Hi, 
I'm trying to use the lib to classify the midi track. But I met the python environment config.
So, can I ask for a python environment configuration?
Thanks, hope for your reply.

**Comment by ruiguo-bio** [comment]
Hi. I use python 3.6.5, and python 3.4-3.7 should all work.

I add a requirements.txt, please install the requirements by `pip install -r requirements.txt`

Hope that will help!

**Comment by lzxzy** [comment]
> Hi. I use python 3.6.5, and python 3.4-3.7 should all work.
> 
> I add a requirements.txt, please install the requirements by `pip install -r requirements.txt`
> 
> Hope that will help!

Thanks for your reply, I'll have a try!
