### ISSUE TITLE
Thank you for the classifier code!

### ISSUE THREAD

**Issue by asigalov61** [ruiguo-bio/midi-miner#5]
@ruiguo-bio Hey bro!

Thanks for the repo and the classifier code in particular. I was able to make a very nice MIDI classifier for myself.

Check it out if you like: 

https://github.com/asigalov61/tegridy-tools/blob/main/tegridy-tools/notebooks/ClassyMIDI_Classifier_and_Songs_Names_Generator.ipynb

Thanks again and I will continue exploring your repo and your proposal/paper.

Great that they have accepted your paper at AI for Music Creativity. I did not make the cut in 2020 :( lol

Sincerely,

Alex

**Comment by ruiguo-bio** [comment]
Hi Alex. I'm very glad you make good use of the code here. If you have any issue please let me know. I'm also working on AI music generation system with different track control(track polyphony,density etc.) Keep an eye on this and I will upload a notebook in the near future.

Best.

Rui

**Comment by asigalov61** [comment]
@ruiguo-bio Hey Rui,

You are welcome.

Yes, I will let you know of any issues. In fact, I think you need to bump pretty_midi support as they have made a few changes in the latest update. I think I resolved it in my copy but you might want to fix it in your repo. https://github.com/ruiguo-bio/midi-miner/issues/4

Yes, polyphonic music is difficult to model so I would be very interested in seeing your solution/take on this problem. I will most certainly keep an eye on your repo. Or you can send me a message once you have it ready and want someone to take it for a test drive.

And I will be looking into your tonal tension solution as I think you're onto something there.

Thank you again for sharing your work.

Alex

**Comment by asigalov61** [comment]
@ruiguo-bio Btw, take a look at my Multi-Instrumental model for my GPT2-based Music AI implementation: https://github.com/asigalov61/Optimus-VIRTUOSO/tree/main/Dataset-Model/

I think I was able to master everything in this implementation except polyphonic performances as they are not easily predictable and really can be anything from what I understand, so yes, I would be very curious to see someone proposing a good solution to the problem.
